server:
  port: 8080
  servlet:
    context-path: /ks

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.243.242/et2108?serverTimezone=UTC
    username: root
    password: 3865571999@Ghy
  redis:
    host: 124.221.243.242
    port: 6379
    #password: etoak

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义配置
image:
  dir: ./src/main/resources/static/pic
  path: /files