server:
  port: 56790
spring:
  application:
    name: adjust-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3865571999@Ghy
    url: jdbc:mysql://124.221.243.242/voika?serverTimezone=UTC
  cloud:
    nacos:
      discovery:
        namespace: voika
        server-addr: 124.221.243.242:8848