server:
  port: 30793
  servlet:
    context-path: /adjust
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3865571999@Ghy
    url: jdbc:mysql://124.221.243.242/voika?serverTimezone=UTC
  redis:
    host: 124.221.243.242
    port: 6379

pagehelper:
  # 合理化分页参数,
  # 当传入的pageNum<=0时, 默认查询第一页;
  # 当传入的pageNum>总页数时, 默认查询最后一页
  reasonable: true

logging:
  level:
    com.etoak.mapper: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置区域
myConfig:
