server:
  port: 8083
  servlet:
    context-path: /edge-adjust

spring:
  datasource:
    username: root
    password: etoak2108
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/et2108?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true